export const paths = {
  home: '/',
  explore: '/explore',
  services: '/services',
  serviceDetails: '/services/:serviceId',
  providers: '/providers',
  providerProfile: '/providers/:providerId',
  providerRequest: '/provider-request',
  login: '/login',
  register: '/register',
  feed: '/feed',
  profile: '/profile',
  notifications: '/notifications',
  chats: '/chats',
  chatConversation: '/chats/:conversationId',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminProviderRequests: '/admin/provider-requests',
  adminReports: '/admin/reports',
}
